apiVersion: v1
kind: Service
metadata:
  name: chat-app-client-service
spec:
  ports:
  - port: 80
    targetPort: chat-app-client-port
    protocol: TCP
  selector:
    app: chat-app-client
  type: LoadBalancer
