apiVersion: v1
kind: Service
metadata:
  name: chat-app-server-service
spec:
  ports:
  - port: 80
    targetPort: chat-app-server-port
    protocol: TCP
  selector:
    app: chat-app-server
  type: LoadBalancer
