# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app/server

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install server-side dependencies
RUN npm install

# Copy the rest of the server application code
COPY . .

# Expose the port on which your server listens
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]

